export const users = [
   
        {
          nama: "Abel Nariko Setyaki",
          nim: "230211033",
          divisi: "UI/UX",
          lolos: false,
        },
        {
          nama: "Aden Sukma Wijaya",
          nim: "230209065",
          divisi: "Kominfo",
          lolos: true,
        },
        {
          nama: "Adzania Rizki Dewani",
          nim: "230202049",
          divisi: "Mobile",
          lolos: true,
        },
        {
          nama: "Akmal Adi Pramana",
          nim: "230209002",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Alfito Dwi Aditya",
          nim: "230202002",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Amanda Bunga Lestari",
          nim: "230209003",
          divisi: "Kominfo",
          lolos: false,
        },
        {
          nama: "Amanda Dwi Safitri",
          nim: "230102050",
          divisi: "Kominfo",
          lolos: false,
        },
        {
          nama: "Amanda Nur Atika",
          nim: "230202051",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Ambar Icah Suryaningrum",
          nim: "230210025",
          divisi: "Sekretaris",
          lolos: false,
        },
        {
          nama: "Amel Adellia Fahrani",
          nim: "230102026",
          divisi: "Mobile",
          lolos: false,
        },
        {
          nama: "Ana Febri Salusi",
          nim: "230202027",
          divisi: "Humas",
          lolos: false,
        },
        {
          nama: "Anggie Nurul Aprilia",
          nim: "230202074",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Anisatun Faoziah Afni Nurjanah",
          nim: "230302075",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Arya Dirham Wijaya Kusumah",
          nim: "230202054",
          divisi: "Data",
          lolos: false,
        },
        {
          nama: "Ashyfa Fitria Syahda",
          nim: "230309005",
          divisi: "UI/UX",
          lolos: false,
        },
        {
          nama: "Aulia Fitri Nur Azizah",
          nim: "230102055",
          divisi: "Humas",
          lolos: true,
        },
        {
          nama: "Azka Syams Maulana",
          nim: "230202004",
          divisi: "Web",
          lolos: true,
        },
        {
          nama: "Bikra Abna Filqiyast Dzaki",
          nim: "230302005",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Danda Prayogi Wijaya",
          nim: "230309069",
          divisi: "Data",
          lolos: false,
        },
        {
          nama: "Danu Rifanli Amin",
          nim: "230211040",
          divisi: "Mobile",
          lolos: false,
        },
        {
          nama: "Davu Andrias Dzakwan",
          nim: "230102077",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Devi Aryani",
          nim: "230102057",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Devia Herena Kippuw",
          nim: "230202031",
          divisi: "Sekretaris",
          lolos: true,
        },
        {
          nama: "Dewi Mona Rizki",
          nim: "230102058",
          divisi: "Data",
          lolos: false,
        },
        {
          nama: "Dewina Aulia Az Zahra",
          nim: "230302032",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Dewo Veteranto",
          nim: "230209071",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Dimas Arya Nugraha",
          nim: "230202033",
          divisi: "Sekretaris",
          lolos: false,
        },
        {
          nama: "Dina Apriliani",
          nim: "230209041",
          divisi: "Data",
          lolos: true,
        },
        {
          nama: "Ego Irfandi",
          nim: "230202007",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Eka Wulan Yuniarsih",
          nim: "230202059",
          divisi: "Bendahara",
          lolos: true,
        },
        {
          nama: "Esnaeni Wulan Andari",
          nim: "230102008",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Eval Putra Parasdika",
          nim: "230202009",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Fahmi Fathurrohman",
          nim: "230202034",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Fassha Fanny Purwanto",
          nim: "230202035",
          divisi: "Mobile",
          lolos: true,
        },
        {
          nama: "Fathan Mubina Ansori",
          nim: "230109009",
          divisi: "Data",
          lolos: false,
        },
        {
          nama: "Fatimah Azzahra",
          nim: "230102081",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Ferina Sheren Nurlita Anggraeni",
          nim: "230302036",
          divisi: "Mobile",
          lolos: true,
        },
        {
          nama: "Galih Fitria Fijar Rofiqoh",
          nim: "230302060",
          divisi: "Kominfo",
          lolos: true,
        },
        {
          nama: "Hafidz Fauzi",
          nim: "230209045",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "HANA KURNIA AYU",
          nim: "23020262",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Ibnu Mustova",
          nim: "230209010",
          divisi: "Mobile",
          lolos: false,
        },
        {
          nama: "Ihza Awaludin",
          nim: "230209047",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "INDRA AJIYANTO",
          nim: "230102083",
          divisi: "Web",
          lolos: true,
        },
        {
          nama: "IRMA SENA MARIYANA",
          nim: "230202084",
          divisi: "Sekretaris",
          lolos: false,
        },
        {
          nama: "Ivan Rifqi Ardiyatno",
          nim: "230311016",
          divisi: "UI/UX",
          lolos: false,
        },
        {
          nama: "IWAN CAHYO PAMBUDI",
          nim: "230309048",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Ji Rizky Cahyusna",
          nim: "230102063",
          divisi: "Bendahara",
          lolos: false,
        },
        {
          nama: "Josindo Radit Albaran",
          nim: "230302064",
          divisi: "Data",
          lolos: false,
        },
        {
          nama: "Katrina Devianti",
          nim: "230102037",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Khalda Nur Resita",
          nim: "230211018",
          divisi: "Kominfo",
          lolos: false,
        },
        {
          nama: "Khidir Afwan Amlabar",
          nim: "230202014",
          divisi: "web",
          lolos: true,
        },
        {
          nama: "Koka Belva Faustina",
          nim: "230309014",
          divisi: "UI/UX",
          lolos: true,
        },
        {
          nama: "Kristian Dimas Adi Wicaksono",
          nim: "230302065",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Lutfi Ahmad Paradiansyah",
          nim: "230209015",
          divisi: "Web",
          lolos: true,
        },
        {
          nama: "Luthfiana Putri Salsabila",
          nim: "230302066",
          divisi: "Sekretaris",
          lolos: false,
        },
        {
          nama: "M Ridho Fatahilah",
          nim: "230209016",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Marshella Angellica",
          nim: "230209049",
          divisi: "Humas",
          lolos: false,
        },
        {
          nama: "Mayang Maharani",
          nim: "230202067",
          divisi: "Humas",
          lolos: false,
        },
        {
          nama: "Meilita Ayu Nur Khasanah",
          nim: "230102038",
          divisi: "Web",
          lolos: true,
        },
        {
          nama: "Muhamad Ramadani",
          nim: "230109050",
          divisi: "Mobile",
          lolos: true,
        },
        {
          nama: "Muhamad Subhi Adzani",
          nim: "230202017",
          divisi: "Kominfo",
          lolos: false,
        },
        {
          nama: "Muhammad Abi Adzan Maulana",
          nim: "230202068",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "MUHAMMAD ARFAZZUHAILI",
          nim: "230202086",
          divisi: "Humas",
          lolos: false,
        },
        {
          nama: "Muhammad Bintang Aditya Saputra",
          nim: "230109051",
          divisi: "Humas",
          lolos: true,
        },
        {
          nama: "Muhammad Irfan",
          nim: "230209082",
          divisi: "Data",
          lolos: false,
        },
        {
          nama: "Muhammad Ivan Rasad",
          nim: "230309052",
          divisi: "Mobile",
          lolos: false,
        },
        {
          nama: "Muhammad Rifa'i",
          nim: "230202016",
          divisi: "Web",
          lolos: true,
        },
        {
          nama: "Muhammad Rizqi Nurrahman",
          nim: "230202087",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Muhammad Zaki Fatahillah",
          nim: "230211055",
          divisi: "UI/UX",
          lolos: false,
        },
        {
          nama: "Musyaffa Achya",
          nim: "230309018",
          divisi: "Humas",
          lolos: true,
        },
        {
          nama: "Nalindra Driyawan Thahai",
          nim: "230202070",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Naufal Marzuqattaqi",
          nim: "230309085",
          divisi: "Data",
          lolos: false,
        },
        {
          nama: "Naura Yaffa Kamila",
          nim: "230209024",
          divisi: "Data",
          lolos: false,
        },
        {
          nama: "Prima Sukma Permana",
          nim: "230209086",
          divisi: "Data",
          lolos: false,
        },
        {
          nama: "Rahmat Mulyadi",
          nim: "230109057",
          divisi: "Data",
          lolos: false,
        },
        {
          nama: "Ramadhani Basith Razaky",
          nim: "230309027",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Raychan Effendy Putra",
          nim: "230309088",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Rayyan Rabbani P",
          nim: "230209058",
          divisi: "Data",
          lolos: false,
        },
        {
          nama: "RENGGA LAHANI",
          nim: "230209059",
          divisi: "Data",
          lolos: false,
        },
        {
          nama: "Revano Augustofa",
          nim: "230102071",
          divisi: "UI/UX",
          lolos: false,
        },
        {
          nama: "Rifqi Firmansyah",
          nim: "230109029",
          divisi: "Mobile",
          lolos: false,
        },
        {
          nama: "Rina Nur Rohmah",
          nim: "230102021",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Risky Bagus Pangestu",
          nim: "230311026",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Rizki Khomsatun Barokah",
          nim: "230102022",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Septiana Lestari",
          nim: "230202089",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Shela Jaya Andini",
          nim: "230302044",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Suci Cahya Nabila",
          nim: "230209061",
          divisi: "Humas",
          lolos: false,
        },
        {
          nama: "Wahyu Nur Cahyo",
          nim: "230211031",
          divisi: "Divisi UI/UX",
          lolos: true,
        },
        {
          nama: "Windy Anggita Putri",
          nim: "230102072",
          divisi: "Web",
          lolos: false,
        },
        {
          nama: "Yusuf Efendi",
          nim: "230102096",
          divisi: "Web",
          lolos: false,
        }
        ,
        {
          nama: "Andin Ardelina Saputri ",
          nim: "230102052",
          divisi: "Web",
          lolos: false,
        }
      
]